# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Meditation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Meditation

  pod 'AppCenter'
 
  pod 'Charts'

  pod 'CodableFirebase', '0.2.0'

  pod 'Firebase/Analytics', '8.6.0'

  pod 'Firebase/Auth', '8.6.0'

  pod 'Firebase/Database', '8.6.0'

  pod 'Firebase/Firestore', '8.6.0'

  pod 'Firebase/Storage', '8.6.0'

  pod 'Kingfisher', '7.0'

  pod 'PKHUD', '~> 5.0'

  pod 'SkyFloatingLabelTextField', '3.8'

end
